services:
  bot:
    #image: prinshertog/discord-alfred-bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: ./.env
        required: true
    depends_on:
      mongodb:
        condition: service_healthy
    restart: always
  mongodb:
    image: mongo:4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - type: bind
        source: ./dockerdata
        target: /data/db
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "mongodb://user:pass@localhost:27017/admin", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
