services:
  # bot:
  #   #image: prinshertog/discord-alfred-bot
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - CONN_STR=mongodb://user:pass@mongodb:27017
  #     - TOKEN=
  #     - CLIENT_ID=
  #     - GUILD_ID=
  #     - DB_NAME=bot-db
  #     - BOT_STATUS_MSG="Vengeance!"
  #     - BOT_STATUS="online"
  #     - MUSIC_FOLDER=/app/music
  #   volumes:
  #     - ./music:/app/music
  #   depends_on:
  #     - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - 27017:27017
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - data:/data/db

volumes:
  data: