name: Test run creation of docker image.

on:
  pull_request:
    branches: [ "main", "dev" ]
  

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build docker image for application
      run: docker build . -t "prinshertog/discord-alfred-bot"
